### ISSUE TITLE
Details of implementation

### ISSUE THREAD

**Issue by szyvcdc** [mh0797/interPlan#9]
Hi, Marcel，

I implore for the more details of the tuplan-garage-llm-baselines implementation on the interplan, such as how your .sh file is configured.

**Comment by szyvcdc** [comment]
My sh. file is as follows:

**Comment by szyvcdc** [comment]
Just list nuplan as a example:

SPLIT=val14_split
CHALLENGE=closed_loop_reactive_agents
CHECKPOINT=/home/usr/.cache/modelscope/hub/shakechen/Llama-2-7b-chat-hf
NUPLAN_DEVKIT_ROOT=/home/usr/nuplan-devkit

python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py \
+simulation=$CHALLENGE \
planner=huggingface_llm_driver_pdmpp_planner \
planner.huggingface_llm_driver_pdmpp_planner.checkpoint_path=$CHECKPOINT \
scenario_filter=$SPLIT \
scenario_builder=nuplan \
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]"

**Comment by mh0797** [comment]
These scripts look good. What exactly is your question regarding them?

**Comment by szyvcdc** [comment]
Well, when I run, it has the following problem:
Traceback (most recent call last):
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 378, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 719, in update
    root[key_] = {}
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 310, in __setitem__
    self._format_and_raise(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 482, in _set_item_impl
    self._validate_set(key, value)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 166, in _validate_get
    self._format_and_raise(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
**omegaconf.errors.ConfigKeyError: Key 'openai_llm_driver_pdmpp_planner' is not in struct
    full_key: planner.openai_llm_driver_pdmpp_planner
    object_type=dict**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vcdc/dutjyf/nuplan-devkit/nuplan/planning/script/run_simulation.py", line 118, in <module>
    main()
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 87, in run
    cfg = self.compose_config(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 558, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 146, in load_configuration
    return self._load_configuration_impl(
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/home/vcdc/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 380, in _apply_overrides_to_config
    raise ConfigCompositionException(
**hydra.errors.ConfigCompositionException: Could not override 'planner.openai_llm_driver_pdmpp_planner.checkpoint_path'.
To append to your config use +planner.openai_llm_driver_pdmpp_planner.checkpoint_path=/home/vcdc/.cache/modelscope/hub/shakechen/Llama-2-7b-chat-hf**

**Comment by mh0797** [comment]
You have to use this version of tuple_garage: https://github.com/mh0797/tuplan_garage_llm_baselines

**Comment by szyvcdc** [comment]
Thanks for your reply, after trying again and again I have run it correctly, thanks again！
